name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Install Apache + PHP + MySQL
    - name: Install LAMP stack
      run: |
        sudo apt update
        sudo apt install apache2 php libapache2-mod-php mysql-server -y
        sudo systemctl start apache2
        sudo systemctl start mysql

    # Create database
    - name: Create MySQL Database
      run: |
        sudo mysql -u root -e "CREATE DATABASE bankms;"

    # Import SQL file (IMPORTANT: change file name if needed)
    - name: Import Database
      run: |
        sudo mysql -u root bankms < bankms.sql

    # Copy project to Apache web root
    - name: Copy project to Apache
      run: |
        sudo cp -r . /var/www/html/bankms
        sudo chmod -R 777 /var/www/html/bankms
        sudo systemctl restart apache2

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Wait few seconds for Apache
    - name: Wait for server
      run: sleep 5

    - name: Run Playwright Test
      run: npx playwright test tests/userlogin.spec.ts

    - name: Upload Playwright HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
